### ISSUE TITLE
g5k-checks is not compatible with Ohai version 7 or above

### ISSUE THREAD

**Issue by priteau** [grid5000/g5k-checks#7]
When first porting g5k-checks to Chameleon, I had to use the latest Ohai 6 version, as Ohai 7 or above would fail. Here is the error message thrown by `g5k-checks -v` when using Ohai 8.12.1.

```
[2016-03-16T10:45:38+00:00] WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.
[2016-03-16T10:45:38+00:00] WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.
[2016-03-16T10:45:38+00:00] WARN: [DEPRECATION] Plugin at /usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks/ohai/cpu.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html
[2016-03-16T10:45:38+00:00] WARN: [DEPRECATION] Plugin at /usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks/ohai/disk.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html
[2016-03-16T10:45:38+00:00] WARN: [DEPRECATION] Plugin at /usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks/ohai/network_adapters.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-03-16T10:45:38+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
/usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks/spec/disk/disk_spec.rb:13:in `block in <top (required)>': undefined method `block_device' for #<Ohai::System:0x00000002bdbb48> (NoMethodError)
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:246:in `module_eval'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:246:in `subclass'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:232:in `describe'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/dsl.rb:18:in `describe'
    from /usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks/spec/disk/disk_spec.rb:1:in `<top (required)>'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
    from /usr/share/gems/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
    from /usr/local/share/gems/gems/g5k-checks-0.5.1/lib/g5kchecks.rb:86:in `run'
    from /usr/local/share/gems/gems/g5k-checks-0.5.1/bin/g5k-checks:80:in `<top (required)>'
    from /usr/local/bin/g5k-checks:23:in `load'
    from /usr/local/bin/g5k-checks:23:in `<main>'
```

**Comment by lnussbaum** [comment]
g5k-checks now uses ohai 8
